config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'welcome/index'

  resources :articles do
    resources :comments

  end


  root 'welcome#index'
  resources :categories do
    resources :articles
  end

  get 'signup', to: 'users#new'
  resources :users

  controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
     end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

  validates :title, :text, presence: true, length: {minimum: 5}
  validates :title, uniqueness: true
  validates_attachment_content_type :image, content_type: [/\Aimage/]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates_associated :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :nickname, :email, :password, presence: true
  validates :nickname, uniqueness: true, length: {maximum: 50}
  validates :email, length: {maximum: 255}, uniqueness: {case_sensitive: false}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session


  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def index
    @articles = Article.all.order(:title)
  end
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)


    if @article.save
      redirect_to @article
    else
      render 'new'
    end

  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to @article
  end


  private
  def article_params
    params.require(:article).permit(:title, :text, :category_id, :image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :current_user, only: [:index, :show]


  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end


  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to articles_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/articles'
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/login'
    else
      render 'new'
    end
  end



  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.slim
= form_for @article, html: { multipart: true }, local: true do |form|
  - if @article.errors.any?
    #error_explanation
      h2
        = pluralize(@article.errors.count, "error")
        |  prohibited this article from being saved: 
      ul
        - @article.errors.full_messages.each  do |msg|
          li
            = msg
  p
    = form.label :title
    br
    = form.text_field :title
  p
    = form.label :text
    br
    = form.text_area :text
  p
    = form.collection_select :category_id, Category.order(:name), :id, :name, class: 'span12'
  p
    = form.file_field :image
  p
    = form.submit

app/views/articles/edit.html.slim
h1
  | Edit article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/index.html.slim
- if current_user
  ul
    li
      = current_user.nickname
    li
      = link_to "Log out", 'logout', method: :delete
- else
    ul
      li
        = link_to 'Login',  "/login"
      li
        = link_to 'Signup', "/signup"


h1
  | Listing articles
table
  tr
    th
      | Title
    th
      | Text
    th
  - @articles.each do |article|
    tr
      td
        = article.title
      td
        = article.text
      td
        = image_tag article.image.url(:thumb)
      td
        = link_to 'Show', article_path(article)
      td
        = link_to 'Edit', edit_article_path(article)
      td
        = link_to 'Delete', article_path(article),
                       method: :delete,
                       data: { confirm: 'Are you sure?'}
  =' link_to 'New article', new_article_path
  br
  = link_to 'Categories',  categories_path

app/views/articles/new.html.slim
h1
  | New article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.slim
p
  strong
    ' Category:
  = @article.category.name
p
  strong
    ' Title:
  = @article.title
p
  strong
    ' Text:
  = @article.text
p
  = image_tag @article.image.url(:medium)
h2
  | Comments
= render 'comments/comment'
h2
  | Add a comment:
= render 'comments/form'
=' link_to 'Back', articles_path
= link_to 'Edit', edit_article_path(@article)

app/views/categories/index.html.slim
table
  tr
    th
      | Categories
    th
  - @categories.each do |category|
    tr
      td
        = link_to category.name, category_path(category)
      td
        = link_to 'Delete', category_path(category),
                               method: :delete,
                               data: { confirm: 'Are you sure?'}
  =' link_to 'New Category', new_category_path
  br
  = link_to 'Back to articles', articles_path

app/views/categories/new.html.slim
= form_with model: @category,  local: true do |form|
  - if @category.errors.any?
    #error_explanation
      h2
        = pluralize(@category.errors.count, "error")
        |  prohibited this article from being saved: 
      ul
        - @category.errors.full_messages.each  do |msg|
          li
            = msg
  p
    = form.label :name
    br
    = form.text_field :name
  p
    = form.submit
= link_to 'Back', categories_path

app/views/categories/show.html.slim
p
  strong
    ' Category:
  = @category.name
table
  tr
    th
      | Title
    th
      | Text
    th
  - @category.articles.each do |article|
    tr
      td
        = article.title
      td
        = article.text
      td
        = image_tag article.image.url(:thumb)
      td
        = link_to 'Show', article_path(article)
      td
        = link_to 'Edit', edit_article_path(article)
      td
        = link_to 'Delete', article_path(article),
                               method: :delete,
                               data: { confirm: 'Are you sure?'}
= link_to 'Back', categories_path

app/views/comments/_comment.html.slim
- @article.comments.each do |comment|
  p
    strong
      ' Commenter:
    = comment.commenter
  p
    strong
      ' Comment:
    = comment.body
  p
    = link_to 'Destroy Comment', [comment.article, comment],
                     method: :delete,
                     data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.slim
= form_with(model: [ @article, @article.comments.build ], local: true) do |form|
  p
    = form.label :commenter
    br
    = form.text_field :commenter
  p
    = form.label :body
    br
    = form.text_area :body
  p
    = form.submit

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/users/new.html.slim
h1
  | Sign up

= form_for @user, html: { multipart: true }, local: true do |form|
  - if @user.errors.any?
    #error_explanation
      h2
        = pluralize(@user.errors.count, "error")
        |  prohibited this article from being saved:
      ul
        - @user.errors.full_messages.each  do |msg|
          li
            = msg
  p
    = form.label :nickname
  br
    = form.text_field :nickname
  p
    = form.label :email
  br
    = form.text_field :email
  p
    = form.label :password
  br
    = form.password_field :password
  br
    = form.password_field :password_confirmation, :placeholder => "Confirm password"
  p
    = form.submit

  p
    = link_to 'Back', "/login"

app/views/welcome/index.html.slim
h1
  | Hello, Rails!
= link_to 'My blog', controller: 'articles'